import type { Therapist } from './types';

export const THERAPISTS_DATA: Therapist[] = [
  {
    id: '1',
    name: 'Dra. Ana García',
    photoUrl: 'https://picsum.photos/seed/therapist1/200/200',
    rating: 4.9,
    reviewsCount: 85,
    specialties: ['Ansiedad', 'Depresión', 'Terapia de Pareja'],
    pricePerSession: 50,
    languages: ['Español', 'Inglés'],
    verified: true,
    credentials: 'Lic. en Psicología, Univ. de Buenos Aires. Mat. 12345',
    bio: 'Con más de 10 años de experiencia, mi enfoque se centra en la terapia cognitivo-conductual para ayudarte a superar tus desafíos.',
  },
  {
    id: '2',
    name: 'Dr. Carlos Rodríguez',
    photoUrl: 'https://picsum.photos/seed/therapist2/200/200',
    rating: 4.8,
    reviewsCount: 72,
    specialties: ['Estrés', 'Adicciones', 'Autoestima'],
    pricePerSession: 55,
    languages: ['Español'],
    verified: true,
    credentials: 'Psicólogo Clínico, Univ. Nacional de Colombia. Reg. 67890',
    bio: 'Especialista en terapia humanista y mindfulness. Juntos encontraremos las herramientas para tu bienestar emocional.',
  },
  {
    id: '3',
    name: 'Dra. Sofía Martínez',
    photoUrl: 'https://picsum.photos/seed/therapist3/200/200',
    rating: 4.9,
    reviewsCount: 91,
    specialties: ['Terapia Familiar', 'Trastornos Alimenticios', 'Ansiedad'],
    pricePerSession: 60,
    languages: ['Español', 'Catalán'],
    verified: true,
    credentials: 'Dra. en Psicología, Univ. de Barcelona. Col. 10112',
    bio: 'Mi objetivo es crear un espacio seguro para explorar dinámicas familiares y personales, promoviendo la comunicación y el cambio.',
  },
  {
    id: '4',
    name: 'Dr. Javier López',
    photoUrl: 'https://picsum.photos/seed/therapist4/200/200',
    rating: 4.7,
    reviewsCount: 65,
    specialties: ['Depresión', 'Duelo', 'Crecimiento Personal'],
    pricePerSession: 45,
    languages: ['Español', 'Inglés'],
    verified: false,
    credentials: 'Máster en Psicoanálisis, Univ. Complutense de Madrid. Colegiado 13145',
    bio: 'A través de la escucha activa, te acompañaré en el proceso de entender y sanar tus heridas emocionales.',
  },
  {
    id: '5',
    name: 'Dra. Laura Fernández',
    photoUrl: 'https://picsum.photos/seed/therapist5/200/200',
    rating: 5.0,
    reviewsCount: 112,
    specialties: ['Terapia de Pareja', 'Sexualidad', 'Comunicación'],
    pricePerSession: 70,
    languages: ['Español'],
    verified: true,
    credentials: 'Especialista en Terapia Sistémica, ITAD. Mat. 15161',
    bio: 'Apasionada por ayudar a las parejas a construir relaciones más fuertes, saludables y satisfactorias.',
  },
  {
    id: '6',
    name: 'Dr. David Pérez',
    photoUrl: 'https://picsum.photos/seed/therapist6/200/200',
    rating: 4.8,
    reviewsCount: 88,
    specialties: ['Ansiedad', 'Fobias', 'TOC'],
    pricePerSession: 52,
    languages: ['Español', 'Inglés', 'Francés'],
    verified: true,
    credentials: 'Psicólogo Sanitario, Univ. de Valencia. CV-17181',
    bio: 'Utilizo técnicas de exposición y prevención de respuesta para ayudarte a recuperar el control sobre la ansiedad y tus miedos.',
  },
];
