export const SUGGESTIONS_FALLBACK = [
  "¿Cómo puedo lidiar con el estrés en el trabajo?",
  "Me siento desmotivado últimamente, ¿qué puedo hacer?",
  "Quiero mejorar mis hábitos de sueño, ¿algún consejo?",
  "He tenido un mal día y necesito desahogarme.",
  "¿Cuáles son los beneficios de la meditación mindfulness?",
  "Siento que estoy procrastinando mucho, ¿cómo puedo evitarlo?",
  "¿Cómo puedo establecer límites saludables con los demás?",
  "Me cuesta mucho concentrarme, ¿tienes alguna técnica?",
  "¿Qué estrategias existen para manejar la ansiedad social?",
  "Quiero desarrollar más mi autoconfianza.",
  "¿Cómo puedo comunicarme de manera más asertiva?",
  "Siento que estoy atrapado en una rutina, ¿cómo puedo salir de ella?",
  "¿Cómo puedo lidiar con pensamientos negativos recurrentes?",
  "Tengo problemas para tomar decisiones importantes.",
  "Me siento solo, ¿qué puedo hacer para conectar con otros?",
  "¿Cómo puedo perdonarme por errores del pasado?",
  "Quiero aprender a manejar mejor mi tiempo y ser más productivo.",
  "¿Qué hago si siento que no encajo en ningún lugar?",
  "¿Cómo puedo cultivar una mentalidad más positiva?",
  "Siento que la gente no me entiende.",
  "¿Cómo puedo superar el miedo al fracaso?",
  "Necesito encontrar un mejor equilibrio entre mi vida personal y laboral.",
  "¿Cómo puedo ser más resiliente ante las adversidades?",
  "Me siento abrumado por mis responsabilidades, ¿qué hago?"
];
