'use client';

import { useState, useCallback, memo, useEffect, useMemo, useRef } from 'react';
import type { Chat, Message, ProfileData, CachedProfile } from '@/lib/types';
import { generateChatTitle, getAIResponse, getSmartComposeSuggestions } from '@/app/actions';
import { useToast } from '@/hooks/use-toast';
import ChatMessages from './chat-messages';
import ChatInput from './chat-input';
import { useIsMobile } from '@/hooks/use-mobile';
import { SidebarTrigger } from '@/components/ui/sidebar';
import { useAuth, useCollection, useFirestore } from '@/firebase';
import { collection, query, orderBy, Timestamp, doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore';
import { updatePsychologicalBlueprint } from '@/ai/flows/update-psychological-blueprint';
import { v4 as uuidv4 } from 'uuid';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';
import type { SecurityRuleContext } from '@/firebase/errors';


interface ChatPanelProps {
  chat: Chat;
  appendMessage: (chatId: string, message: Omit<Message, 'id'>) => Promise<void>;
  updateChatTitle: (chatId: string, title: string) => Promise<void>;
}

function ChatPanel({ chat, appendMessage, updateChatTitle }: ChatPanelProps) {
  const [isResponding, setIsResponding] = useState(false);
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const suggestionTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const [isRefreshingSuggestions, setIsRefreshingSuggestions] = useState(false);

  const { toast } = useToast();
  const isMobile = useIsMobile();
  const { user } = useAuth();
  const firestore = useFirestore();
  const [cachedProfile, setCachedProfile] = useState<ProfileData | null>(null);

  const messagesQuery = useMemo(
    () =>
      user?.uid && firestore && chat.id
        ? query(
            collection(firestore, `users/${user.uid}/chats/${chat.id}/messages`),
            orderBy('timestamp', 'asc')
          )
        : undefined,
    [user?.uid, firestore, chat.id]
  );
  
  const { data: messages, loading: messagesLoading } = useCollection<Message>(messagesQuery);
  
  // Load cached profile on component mount
  useEffect(() => {
    if (user) {
      const storageKey = `psych-profile-${user.uid}`;
      const cachedItem = localStorage.getItem(storageKey);
      if (cachedItem) {
        try {
          const data: CachedProfile = JSON.parse(cachedItem);
          setCachedProfile(data.profile);
        } catch (e) {
          console.error("Failed to parse cached profile", e);
          localStorage.removeItem(storageKey);
        }
      }
    }
  }, [user]);


  const triggerBlueprintUpdate = useCallback(async (currentMessages: Message[]) => {
      if (!user) return;

      const stateDocRef = doc(firestore, `users/${user.uid}/chatbotState/main`);
      try {
        const previousStateSnap = await getDoc(stateDocRef);
        const previousBlueprint = previousStateSnap.exists()
            ? JSON.stringify(previousStateSnap.data().blueprint, null, 2)
            : "No previous state. This is my first reflection.";

        const fullChatHistory = currentMessages.map(msg => {
            const date = msg.timestamp && typeof (msg.timestamp as any).toDate === 'function' 
              ? (msg.timestamp as Timestamp).toDate() 
              : new Date();
            return `[${date.toISOString()}] ${msg.role}: ${msg.content}`;
          }).join('\n');
        
        const newBlueprint = await updatePsychologicalBlueprint({
            fullChatHistory,
            previousBlueprint,
        });

        const dataToSave = {
            blueprint: newBlueprint,
            updatedAt: serverTimestamp(),
        };
        await setDoc(stateDocRef, dataToSave);

      } catch (error: any) {
         if (error.code === 'permission-denied') {
            const permissionError = new FirestorePermissionError({
              path: stateDocRef.path,
              operation: 'write',
              requestResourceData: { blueprint: 'Generated by AI', updatedAt: 'Server Timestamp'}
            } satisfies SecurityRuleContext);
            errorEmitter.emit('permission-error', permissionError);
         } else {
             console.error("Error updating blueprint:", error);
         }
      }
  }, [user, firestore]);

  const fetchSuggestions = useCallback(async () => {
    if (!messages || messages.length === 0) return;
    setIsRefreshingSuggestions(true);
    try {
        const historyString = messages.map((m) => `${m.role}: ${m.content}`).join('\n');
        const newSuggestions = await getSmartComposeSuggestions(historyString);
        setSuggestions(newSuggestions.slice(0, 3));
    } catch (error) {
        console.error("Error fetching suggestions", error);
    } finally {
        setIsRefreshingSuggestions(false);
    }
  }, [messages]);


  const getAIResponseAndUpdate = useCallback(async (currentMessages: Message[]) => {
    if (!user) return;
    setIsResponding(true);
    setSuggestions([]);
    if (suggestionTimeoutRef.current) {
        clearTimeout(suggestionTimeoutRef.current);
    }

    try {
      const historyForAI: Message[] = currentMessages.map(m => ({
          ...m,
          timestamp: m.timestamp instanceof Timestamp ? m.timestamp.toDate() : m.timestamp,
      }));

      const aiResponseContent = await getAIResponse(
        historyForAI,
        user.uid,
        chat.anchorRole || null,
        cachedProfile
      );

      const aiMessage: Omit<Message, 'id'> = {
        role: 'assistant',
        content: aiResponseContent,
        timestamp: Timestamp.now(),
      };
      
      setIsResponding(false); 
      await appendMessage(chat.id, aiMessage);
      
      const updatedMessages = [...currentMessages, { ...aiMessage, id: uuidv4() }];

      // Delayed suggestions logic
      const words = aiResponseContent.split(/\s+/).length;
      const readingTime = Math.max(2000, words * 60); // 60ms per word, minimum 2 seconds
      
      suggestionTimeoutRef.current = setTimeout(async () => {
         const historyString = updatedMessages.map((m) => `${m.role}: ${m.content}`).join('\n');
         const newSuggestions = await getSmartComposeSuggestions(historyString);
         setSuggestions(newSuggestions.slice(0, 3));
      }, readingTime);


      // Title is generated only if it's the default "Nuevo Chat"
      if (currentMessages.length === 1 && chat.title === 'Nuevo Chat') {
          const userMessage = currentMessages[0];
          const conversationForTitle = `User: ${userMessage.content}\nAssistant: ${aiResponseContent}`;
          const newTitle = await generateChatTitle(conversationForTitle);
          await updateChatTitle(chat.id, newTitle);
      }
      
      if (updatedMessages.length % 5 === 0) {
        triggerBlueprintUpdate(updatedMessages);
      }

    } catch (error) {
        console.error("Error getting AI response:", error);
        setIsResponding(false); // Make sure to turn off responding on error
        toast({
          variant: "destructive",
          title: "Error",
          description: "No se pudo obtener una respuesta de la IA. Por favor, inténtalo de nuevo.",
        });
    }
  }, [user, chat.id, chat.anchorRole, chat.title, appendMessage, updateChatTitle, toast, triggerBlueprintUpdate, cachedProfile]);


  const handleSendMessage = useCallback(async (input: string, imageUrl?: string) => {
    if ((!input || !input.trim()) && !imageUrl) return;
    if (!user) {
        toast({
            variant: "destructive",
            title: "Error",
            description: "Debes iniciar sesión para chatear.",
        });
        return;
    }

    const userMessage: Omit<Message, 'id'> = {
      role: 'user',
      content: input,
      timestamp: Timestamp.now(),
      ...(imageUrl && { imageUrl }),
    };

    const currentMessages = [...(messages || []), { ...userMessage, id: uuidv4() }];
    
    await appendMessage(chat.id, userMessage);
    await getAIResponseAndUpdate(currentMessages);

  }, [user, messages, appendMessage, chat.id, getAIResponseAndUpdate, toast]);

  // Effect to handle the very first response in a new chat
  useEffect(() => {
    // Only trigger if we have exactly one message and it's from the user
    if (messages && messages.length === 1 && messages[0].role === 'user' && !isResponding) {
      getAIResponseAndUpdate(messages);
    }
  }, [messages, isResponding, getAIResponseAndUpdate]);

  useEffect(() => {
    // Clear suggestion timeout on unmount
    return () => {
      if (suggestionTimeoutRef.current) {
        clearTimeout(suggestionTimeoutRef.current);
      }
    };
  }, []);

  const handleClearSuggestions = () => {
    setSuggestions([]);
    if (suggestionTimeoutRef.current) {
        clearTimeout(suggestionTimeoutRef.current);
    }
  };


  return (
    <div className="flex flex-col h-full">
       <header className="flex h-14 items-center justify-between p-2 md:p-4 border-b">
        <div className="flex items-center gap-2">
          {isMobile && <SidebarTrigger />}
           <div className='min-w-0'>
            <h2 className="text-base md:text-lg font-semibold truncate">
              {chat.title}
            </h2>
            {chat.anchorRole && (
              <p className='text-xs text-muted-foreground truncate'>Rol: {chat.anchorRole}</p>
            )}
           </div>
        </div>
      </header>
      <div className="flex-1 overflow-y-auto">
        <ChatMessages messages={messages || []} isResponding={isResponding || messagesLoading} />
      </div>
      <div className="mt-auto px-2 py-4 md:px-4 md:py-4 border-t bg-background/95 backdrop-blur-sm">
        <ChatInput
          onSendMessage={handleSendMessage}
          isLoading={isResponding || messagesLoading}
          suggestions={suggestions}
          onClearSuggestions={handleClearSuggestions}
          onRefreshSuggestions={fetchSuggestions}
          isRefreshingSuggestions={isRefreshingSuggestions}
        />
      </div>
    </div>
  );
}

export default memo(ChatPanel);
